### ISSUE TITLE
Build not failing when it should

### ISSUE THREAD

**Issue by fernandoacorreia** [scoverage/sbt-coveralls#1]
When [running coveralls](https://github.com/mohiva/play-silhouette/blob/18f141c0bbd1d7db3efbde124efc5b03b68b75e7/scripts/ci-build#L17) the build [shows this error messages](https://travis-ci.org/mohiva/play-silhouette/builds/17357942#L529):

```
[error] (scoverage-test:compile) Compilation failed
```

and 

```
Could not find any cobertura.xml files. Has the coverage plugin run?
```

But the build succeeds instead of failing:

```
[success] Total time: 99 s, completed Jan 21, 2014 6:20:55 PM
```

The source code on which this is happening is at [this commit](https://github.com/mohiva/play-silhouette/tree/18f141c0bbd1d7db3efbde124efc5b03b68b75e7).

The build should fail at the first error ("Compilation failed"), but if not, it should certainly fail at the second ("Could not find any cobertura.xml files").

This seems to be related to sbt-coveralls, since running locally `sbt clean scoverage:test; echo $?;` outputs status code 1 as expected. The same happens when running the project's custom `scripts/sbt` loader script.

As a workaround, it fails as it should when tests are explicitly compiled before calling coveralls, as seen [here](https://github.com/mohiva/play-silhouette/pull/70/files).

**Comment by malcolmgreaves** [comment]
@sksamuel any word on this? What was the resolution? I'm having this problem currently (albeit in a different form: some tests fail, coveralls upload succeeds, thus build is marked as passing when it should be failing).

**Comment by sksamuel** [comment]
The coveralls plugin isn't really maintained. It was just ported to this repo as the original author did not wish to maintain it anymore.

**Comment by malcolmgreaves** [comment]
Ah ok, I see. I didn't realize the maintenance situation. Thank you for letting me know! Do you know anyone who is maintaining this plugin? Perhaps I should fork and try to fix it myself?

**Comment by sksamuel** [comment]
@rorygraves and @fommil have done a lot of work on this.

**Comment by fommil** [comment]
@sksamuel that you'll release soon, right? :smile:

**Comment by sksamuel** [comment]
Release as soon as you want, if you have asked elsewhere sorry prob missed
it - I have no access to these things during day at work unless its via my
phone.

**Comment by fommil** [comment]
a release in the next few days would be perfect, thanks!

**Comment by gslowikowski** [comment]
@rorygraves works on coveralls working with `1.0.5-SNAPSHOT` versions of `scoverage-scala-plugin` and `sbt-scoverage` (see https://github.com/scoverage/sbt-scoverage/issues/100#issuecomment-82616782). This version fixes some path and multimodule build issues.
If/when the `1.0.5-SNAPSHOT` compatible version of `coveralls` will be ready and tested, we should release: `1.0.5` version of: `scalas-scoverage-plugin`, `sbt-scoverage` and next version of `sbt-coveralls` in this order.
I have some improvements I want to push to `scalac-scoverage-plugin` before releasing, but haven't had time to test it recently.

**Comment by rorygraves** [comment]
Aplogies all - I've been a bit slow on the testing I have promised to do - I think we can happily release the changes from @fommil  now - and then release a new version after scalac-scoverage-plugin is updated if needed.

**Comment by sksamuel** [comment]
Is master ready to be released as is ?

**Comment by fommil** [comment]
should be

**Comment by gslowikowski** [comment]
@sksamuel I've just updated `publishTo` setting (https://github.com/scoverage/sbt-coveralls/blob/master/build.sbt#L36), you can publish `1.0.0-SNAPSHOT` now (or give me permissions to publish to SBT plugin snapshots repository and I will do it).

To use SBT plugin snapshots in test projects `resolvers += Classpaths.sbtPluginSnapshots` line has to be added to `project/plugins.sbt` file.

**Comment by gslowikowski** [comment]
Its always better to test with publicly available snapshot than one built locally.

**Comment by gslowikowski** [comment]
Hi
I've prepared locally `sbt-coveralls` compatible with `sbt-scoverage` 1.0.5-SNAPSHOT and tested it on your `ensime-server` project.
Check results here: https://coveralls.io/r/gslowikowski/ensime-server (I hope it's publicly browsable). and tell me, what you think.
Additionally, when learning `sbt-coveralls` code base I found some things I don't like. With whom can I discuss it (this issue is not the best place IMO)? Maybe we can use Gitter?

**Comment by sksamuel** [comment]
Yeah start a gitter. Just so you know the coveralls project was inherited,
none of us here wrote it originally.

**Comment by gslowikowski** [comment]
I know, but I don't know If @rorygraves is the leader now? He commits recently.

**Comment by sksamuel** [comment]
There is no "leader" but @rorygraves is doing most of the work.

**Comment by rorygraves** [comment]
@gslowikowski  - the report is broken in at least one way.
If you browse the local aggregate report you should see coverage around 75%
The aggregrate report used to be broken becaues the file links didn't include the module path (or included the full file path - something along those lines), but I think thats addressed.

I've been meaning to fight some more with the sbt-scoverage sbt-coveralls to work out where the break is, but its been a busy week - btw, I've just created https://gitter.im/scoverage/sbt-coveralls

**Comment by rorygraves** [comment]
I've been a bit ad-hoc with it - I'm willing to 'own' it, but time as always is in short supply ;)
