### ISSUE TITLE
Build fails in cross compile due to macros

### ISSUE THREAD

**Issue by sksamuel** [scoverage/sbt-coveralls#105]
See the latest builds at Travis
https://travis-ci.org/scoverage/sbt-coveralls/builds/326138222

Can anyone who knows SBT help fix this? Or tell me what to do?

**Comment by pdolega** [comment]
An attempt to fix this is here: https://github.com/scoverage/sbt-coveralls/pull/110

**Comment by gslowikowski** [comment]
Fixed by #110
