### ISSUE TITLE
doesn't send folder info for sub projects

### ISSUE THREAD

**Issue by Mortimerp9** [scoverage/sbt-coveralls#12]
I have a project with two subprojects: 
https://github.com/quantifind/Sumac

They are each in a separate folder in the repo, but the reports sent to coveralls seem to search for the files at the root of the repo (there is an option to change this, but it sets one subdirectory for the whole repo, which is not the case here):
https://coveralls.io/files/168116601

Could sbt-coveralls figure out that it's working on separate source folders and send the info directly?

**Comment by massenz** [comment]
I don't use `build.scala` - is there a way to disable the plugin without having to resort to one?

**Comment by rpless** [comment]
@massenz You should not need to change to `build.scala`. As long as you have an instance of a `Project` in sbt that represents a subproject, it should work. I took a quick look at Sentinel. My guess is that in the sbt file for your subproject you need to do something like this:
```scala
project.disablePlugins(CoverallsPlugin)
```

**Comment by massenz** [comment]
Thanks @rpless - it still didn't work; adding to the `core` subproject's `build.sbt` the line:
```
lazy val core = (project in file(".")).disablePlugins(CoverallsPlugin)
```
caused SBT to get very angry at me, claiming essentially that I'm undecided individual, wanting to both include and exclude the same thing (which, I guess, would be true).

In the end, IMO, we need the sbt-coveralls plugin to sort itself (at this point, I am even doubtful there is any active maintenance going in there)

**Comment by fommil** [comment]
fixed

**Comment by fommil** [comment]
@rorygraves vote to close as old version

**Comment by rorygraves** [comment]
Fixed on master - needs a release
