### ISSUE TITLE
Support parallel builds (`"parallel": true`)

### ISSUE THREAD

**Issue by huonw** [scoverage/sbt-coveralls#125]
Coveralls supports "parallel builds", i.e. multiple builds all measuring coverage that each get uploaded independently, and aggregated by Coveralls. It seems this is driven by firstly the `parallel` field in a post to the `jobs` endpoint (https://docs.coveralls.io/api-reference), and then a later post to [a web hook](https://docs.coveralls.io/parallel-build-webhook) to indicate completion. `sbt coveralls` doesn't currently expose this. It looks like it is typically done via a `COVERALLS_PARALLEL` environment variable: https://docs.coveralls.io/parallel-build-webhook

**Comment by rolandtritsch** [comment]
Old. Closing. Please reopen when needed.
