### ISSUE TITLE
Add support for GitHub Actions

### ISSUE THREAD

**Issue by ruippeixotog** [scoverage/sbt-coveralls#126]
I'm trying to migrate from Travis to GitHub Actions, but I'm blocked in the coverage uploading step. Coveralls has an [official action] (https://github.com/marketplace/actions/coveralls-github-action), but they only support LCOV files, not cobertura.xml. I can specify the Coveralls repo token as a secret but it won't be available in pull requests, where they are most useful.

Can you add support for authenticating using GITHUB_REPO_TOKEN like the official action does?

**Comment by chuwy** [comment]
Wondering if any of these produce the LCOV format: https://github.com/scoverage/sbt-scoverage/blob/da2dec181d50571d3d5134b94e52d7dbab3ce9c6/src/main/scala/scoverage/ScoverageKeys.scala#L15-L16

**Comment by ruippeixotog** [comment]
They don't, the GitHub Action is looking for a lcov.info file...

@sksamuel, is this plugin still being maintained?
