### ISSUE TITLE
Where is the coveralls.json file ?

### ISSUE THREAD

**Issue by leobenkel** [scoverage/sbt-coveralls#174]
Hello,

I am using 

```scala
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.8.2")
addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.3.1")
```

I run:

```
sbt ";clean; coverage; test; coverageReport; coveralls"
```

I see a message like "uploading 'coveralls.json'" in the `coveralls` step. 

I would like to check out the content of the `coveralls.json` file before it is being sent to coveralls. Where is it located ? 

Thank you !

**Comment by rolandtritsch** [comment]
Old. Closing. Please reopen when needed.
