### ISSUE TITLE
Fix plugin coveralls error handling

### ISSUE THREAD

**Issue by rorygraves** [scoverage/sbt-coveralls#20]
When the plugin fails to upload it gets a StringOutOfBounds because the error response is now a json object not an html document.

This means that the error from the plugin is most unhelpful.

@sksamuel This is more of a mental note for me to fix it.

**Comment by fommil** [comment]
I wanted to fix this, and I can see the problem in the code, but I can't actually locally reproduce the problem. I'll put in a PR which will capture some output.

**Comment by fommil** [comment]
It's also not clear from the https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction docs what the payload contents are really supposed to look like. newlines as `\n`, but nothing about other special chars or UTF-8?

**Comment by lancegatlin** [comment]
I've had this issue as well now for last few months. My logs are here: https://travis-ci.org/S-Mach/s_mach.datadiff and https://travis-ci.org/S-Mach/s_mach.codetools

**Comment by lancegatlin** [comment]
So I just updated all of my repos to stop putting environment variables in the .travis.yml (encrypted) and instead adding them through the Travis-CI website and my issues with this bug have gone away (Note: I still have other issues haha).

**Comment by fommil** [comment]
It will be coincidence. The fix is in my patch, yet to be released.

**Comment by nafg** [comment]
+1

**Comment by fommil** [comment]
close?

**Comment by rorygraves** [comment]
I think this is fixed now.
