### ISSUE TITLE
Issues with scoverage 2.0.6

### ISSUE THREAD

**Issue by jacemale-ovo** [scoverage/sbt-coveralls#222]
Hi,
I've been trying to use the plugin with the latest sbt-scoverage (2.0.6, the only version released for Scala 2.13.10), but I've run into multiple issues after upgrading the plugin:
- initially I was getting `FileNotFound` for `cobertura.xml`, the path this plugin uses seems to no longer be valid, scoverage is generating it under `coverage-report/cobertura.xml` instead of `scoverage-data/coverage-report/cobertura.xml`, I've managed to fix it in my project by setting the `coberturaFile` SBT setting
- after the first issue was fixed, I started seeing a new exception for every single file in the project:
  ```
  IllegalArgumentException: requirement failed: The file ... does not belong to any of the source directories List
  ```
  this one was more difficult to fix as I had to fork this repo and apply a change to how paths are parsed from the XML file, the   file I am seeing on my machine has relative paths, but this plugin seems to assume they're absolute and that doesn't seem to work

Let me know if there's anything I've missed but I think this is indeed an issue between this plugin and sbt-scoverage. I am currently using a fork of this plugin with success, you can see the changes [here](https://github.com/scoverage/sbt-coveralls/compare/main...jacemale-ovo:sbt-coveralls:path-fixes), I am open to creating a pull request.

**Comment by rolandtritsch** [comment]
Hi. This should be fixed now. Thanks for reporting the issue. Please close the issue after you have confirmed that it works. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.5

**Comment by jacemale-ovo** [comment]
It's working now, thanks!
