### ISSUE TITLE
Support parallel builds

### ISSUE THREAD

**Issue by richard-dennehy-ovo** [scoverage/sbt-coveralls#239]
Hi,

We'd like to speed up our CI pipelines by splitting the tests across multiple CI runners and executing these in parallel, but we're running into issues with low test coverage, as each instance generates an incomplete report which are erroneously treated as if they're full reports.

Coveralls supports this exact use case, see [here](https://docs.coveralls.io/parallel-build-webhook), but this plugin currently doesn't support the `parallel` flag mentioned in that doc.

Someone else raised the same issue here https://github.com/scoverage/sbt-coveralls/issues/125 but this was closed without being resolved.

I have a branch https://github.com/richard-dennehy-ovo/sbt-coveralls/tree/support-parallel-builds that I intend to raise a PR from in a moment, would it be possible to get this merged?

Thanks

**Comment by rolandtritsch** [comment]
Hi Richard,

Thanks for the PR. Sorry for the radio silence. I was OOO. I will take a
look at this this week.

Regards ...
    Roland

**Comment by rolandtritsch** [comment]
Hi Richard. This is merged and released. Thanks for the contribution. - RT
