### ISSUE TITLE
Coveralls plugin seems to be running tests multiple times on TravisCI

### ISSUE THREAD

**Issue by holograph** [scoverage/sbt-coveralls#25]
I'm rather new to sbt-coverage and Coveralls, so it's entirely possible I did something wrong, but I basically followed the site instructions. Coverage tests seem to be running, but now my builds on TravisCI seem to [consistently fail](https://travis-ci.org/wix/accord/jobs/38658825) with "GC overhead limit exceeded" errors. The only obvious difference from previous builds is that with the sbt-coveralls plugin, tests seem to be running four times before the VM crashes (instead of the expected single run).

**Comment by fommil** [comment]
@rorygraves vote to close as a configuration error, should be `sbt coverage test coveralls`

**Comment by rorygraves** [comment]
@holograph Are you still seeing this issue - please reopen if you are.  Thanks.

**Comment by holograph** [comment]
I don't recall seeing any traffic on this issue, but I've [re-enabled](https://github.com/wix/accord/commit/83fe714458fc33be1dd15c6d778fc3a05f2c5876) Coveralls way back in December and haven't had any issues since. LGTM :-)
