### ISSUE TITLE
Publish sbt-coveralls plugin with JDK 8?

### ISSUE THREAD

**Issue by mdedetrich** [scoverage/sbt-coveralls#250]
I am getting

```
java.lang.UnsupportedClassVersionError: org/eclipse/jgit/storage/file/FileRepositoryBuilder has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

From https://github.com/mdedetrich/akka-streams-json/actions/runs/4440234230/jobs/7793780169?pr=86.

This is usually caused when you release sbt-plugin with a newer JDK. Would it be possible to release this plugin with JDK 8?

**Comment by rolandtritsch** [comment]
Merged. Published. Released. Thanks for the contribution. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.7

**Comment by ruippeixotog** [comment]
From https://github.com/pureconfig/pureconfig/pull/1484, I believe something went wrong... it looks like sbt-coveralls v1.3.7 still depends on JDK 11 (https://github.com/pureconfig/pureconfig/actions/runs/4584898251/jobs/8096681785?pr=1484).

**Comment by mdedetrich** [comment]
@ruippeixotog Created a PR at https://github.com/scoverage/sbt-coveralls/pull/252 to resolve the problem.

**Comment by ruippeixotog** [comment]
@mdedetrich, is there a chance you can release a new version of sbt-coveralls with https://github.com/scoverage/sbt-coveralls/pull/252 so we can update sbt-coveralls on JDK 8 projects? Thanks!

**Comment by mdedetrich** [comment]
I am not a maintainer so I can't make a release, I would presume @rolandtritsch would have the ability to make a release since he merged my fixes.

**Comment by rolandtritsch** [comment]
Hi All. This week I am at ElixirConfEU in Lisbon/Portugal. Will cut a new
release on Fri or Sat, if that is ok. - RT

**Comment by rolandtritsch** [comment]
> Hi All. This week I am at ElixirConfEU in Lisbon/Portugal. Will cut a new release on Fri or Sat, if that is ok. - RT

Done.
