### ISSUE TITLE
upload fails when there are scala specific version directories

### ISSUE THREAD

**Issue by kpodsiad** [scoverage/sbt-coveralls#267]
I was trying to migrate scache and due to compiler bug I have to write version-specific code. After having scala-2 and scala-3 dirs, CI has started to fail during upload phase in my draft PR https://github.com/kpodsiad/scache/pull/1, see e.g. https://github.com/kpodsiad/scache/actions/runs/5413382887/jobs/9838847866.
Scala 3
```
[error] java.util.NoSuchElementException: key not found: 3/com/evolution/scache/CacheOpsCompat.scala
```
Scala 2
```
[error] java.util.NoSuchElementException: key not found: 2/com/evolution/scache/CacheOpsCompat.scala
```

I've read through plugins settings keys but I don't see any option which can solve my issue with uploading. Is it really an issue or mistake on my end?

**Comment by rolandtritsch** [comment]
Hi @kpodsiad. I can reproduce this. Looking ...

**Comment by rolandtritsch** [comment]
Hi @kpodsiad. Can you try ... - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.9

**Comment by kpodsiad** [comment]
Hey @rolandtritsch, I tried `1.3.9` and it works! Thanks.
