### ISSUE TITLE
Option to just upload

### ISSUE THREAD

**Issue by fernandoacorreia** [scoverage/sbt-coveralls#3]
A continuous integration build should fail if the tests fail, but it shouldn't necessarily fail if there's an error uploading the coverage data to Coveralls.

In the case of Travis CI, this could be achieved by running `sbt scoverage:test` in the main build step, and running `sbt coveralls` in the after_success step.

Unfortunately, the `coveralls` task seems to always run `scoverage:test`, even if has just been executed and the coverage report files are available.

The proposed solution is to add an optional execution target, such as `coveralls:upload`, that would skip running `scoverage:test` and would proceed directly to the next step, to upload the coverage data to Coveralls.

For an example of an impacted project see [this issue](https://github.com/mohiva/play-silhouette/issues/119).

**Comment by malcolmgreaves** [comment]
This is still a problem. For instance, if the tests fail, "sbt coveralls" won't sometimes because the last task to execute is the uploading to coveralls.io. If that upload is successful, then "sbt coveralls" is successful. Does "coverallsFailBuildOnError := true" now make it fail if the tests fail?
