### ISSUE TITLE
401 Content access is protected by token

### ISSUE THREAD

**Issue by rolandtritsch** [scoverage/sbt-coveralls#311]
Right now the `sbt ci-release` task fails with ...
```
java.io.IOException: Failure:java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
```
... which is explained [here][].

To fix this I need the username/password to the SONATYPE account (which I do not have).

@ckipp01 @sksamuel Can you help? Do you have the username/password?

[here]: https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories

**Comment by ckipp01** [comment]
This should be updated now.

**Comment by rolandtritsch** [comment]
![image](https://github.com/user-attachments/assets/c55dfa4f-c699-4f6f-8741-b793e99f6781)

We are back in business.
