### ISSUE TITLE
No coverage data added to coveralls

### ISSUE THREAD

**Issue by muktaa** [scoverage/sbt-coveralls#33]
I have followed exact steps as mentioned in the readme. But I face the following error when I run `sbt coveralls`:

[error] Could not find any cobertura.xml files. Has the coverage plugin run?
[info] Uploading to coveralls.io succeeded: Job #x.y
[info] https://coveralls.io/jobs/xyz
[info] (results may not appear immediately)

I ran `sbt coverage` and `sbt coverage test` (and also `sbt clean coverage test`) before running `sbt coveralls`.

Please help in fixing this issue.

**Comment by c089** [comment]
I'm seeing the same issue. There is a file named `target/scala-2.11/scoverage-data/scoverage.coverage.xml` available.

**Comment by muktaa** [comment]
Here is what helped me, they should update their documentation with 1 missing step in between.

`sbt clean coverage test`
`sbt coverageReport`
`sbt coveralls`

**Comment by c089** [comment]
Thank you @muktaa. I was under the impression that the `coverageReport` task was only to build the HTML files. I'll provide a pull request to improve the documentation.
