### ISSUE TITLE
document the need to add configuration to your build.sbt to enable travis-pro as a service_name

### ISSUE THREAD

**Issue by nh13** [scoverage/sbt-coveralls#37]
I was getting very strange coveralls reports when using this plugin when using travis-pro.  The coverall reports on coveralls.io linked to other repositories and listed branches that did not exist.  I found that the service_name was not being set correctly after talking with coveralls.io support.  I found this old issue on the [xsbt-coveralls-plugin](https://github.com/theon/xsbt-coveralls-plugin/issues/14) project.  I used the same strategy to set the service name in my build.sbt:

```
import CoverallsPlugin.CoverallsKeys._
seq(CoverallsPlugin.singleProject: _*)
coverallsServiceName := "travis-pro"
```

This should be documented somewhere in the README.md, along with overriding other configuration settings in ```CoverallsPlugin.CoverallsKeys```.

**Comment by rorygraves** [comment]
Closing a change has been merged.
