### ISSUE TITLE
files not found for multi-project

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-coveralls#39]
I am putting together a PR for ensime-server that breaks the project into modules

  https://github.com/ensime/ensime-server/pull/841

but the coverage report is down by almost 8% despite it just being a reorganisation!

Also, the links on coveralls don't work in the PR coverage report :crying_cat_face: 

  https://coveralls.io/builds/2013029

**Comment by fommil** [comment]
yeah, looks like the payload to coveralls has the relative path from the module base, rather than the full path from the project base, so it's unable to load the files to show the summaries https://coveralls.io/r/ensime/ensime-server

**Comment by fommil** [comment]
@rorygraves any chance you could look at this? It's probably quite easy to fix the payload.

**Comment by fommil** [comment]
@rorygraves looks like the culprit! https://github.com/scoverage/sbt-coveralls/blob/master/src/main/scala/org/scoverage/coveralls/CoverallPayloadWriter.scala#L88

Needs a `moduleName + "/" +` by the looks of it

**Comment by rorygraves** [comment]
Yeah I can look at this :)

**Comment by rorygraves** [comment]
even easier when someone points out the fix ;)

**Comment by fommil** [comment]
the timing out DebugTest is really annoying me, aarg! I think that is actually the cause of the reduced coverage number.

BTW, did you see coveralls will now do its own threshold checking (with tolerance)? I've removed the test from sbt because we can rely on "coverage jerk" now :smile:

**Comment by fommil** [comment]
this semes to have fixed itself. maybe coveralls.io don't need a full path anymore?
