### ISSUE TITLE
No coverage data added to coverall (bis)

### ISSUE THREAD

**Issue by nrinaudo** [scoverage/sbt-coveralls#45]
This sounds like a clone of issue #33, but it really isn't.

When running `sbt coveralls` after having successfully ran `sbt coverageAggregate` on a multi-modules project, everything seems fine, a new build is successfully created on coveralls.io, but that build has no coverage data.

Here's `sbt coveralls`' output (full build output available [here](https://travis-ci.org/nrinaudo/fetch/jobs/54573596)):
```
[info] Set current project to fetch (in build file:/home/travis/build/nrinaudo/fetch/)
[info] Repository = ./.git
[info] Repository = ./.git
[info] Repository = ./.git
[info] Repository = ./.git
[info] Repository = ./.git
[info] Repository = ./.git
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] https://coveralls.io/jobs/4926893
[info] https://coveralls.io/jobs/4926894
[info] (results may not appear immediately)
[info] (results may not appear immediately)
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] https://coveralls.io/jobs/4926895
[info] (results may not appear immediately)
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] https://coveralls.io/jobs/4926896
[info] (results may not appear immediately)
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] https://coveralls.io/jobs/4926897
[info] (results may not appear immediately)
[info] Uploading to coveralls.io succeeded: Job #125.2
[info] https://coveralls.io/jobs/4926898
[info] (results may not appear immediately)
[success] Total time: 6 s, completed Mar 16, 2015 2:18:53 PM
```

And [here](https://coveralls.io/builds/2123057)'s the corresponding coveralls build.

I'd be happy to perform any diagnosis task that would be considered helpful.

**Comment by rorygraves** [comment]
@nrinaudo  I think this is related to another issue https://github.com/scoverage/sbt-scoverage/issues/91
Does the aggregated local report work for you?  I suspect the paths in the links are wrong as you navigate.
Hoping to break the back of this issue in the next couple of days.

**Comment by nrinaudo** [comment]
Yes, you're absolutely right: my local aggregated HTML report has broken links. Strangely enough, the `scoverage-report` directory also contains a copy of my project's sources, but with path starting from my FS's root.

Let me know if I can do anything to help you get to the root of this.

**Comment by rorygraves** [comment]
I think you are halfway to solving it - I think the absolute paths are being appended where relative paths are needed. Think I know where - just need to get a free evening to get to the bottom of it :)

**Comment by fommil** [comment]
I fixed the coveralls problem yesterday, but we're waiting for a release.

**Comment by nrinaudo** [comment]
Great, good to know. Is it available as a snapshot somewhere, that I can try it and confirm that it does indeed fix this issue?

**Comment by rorygraves** [comment]
you would have to do a publishLocal to try it.

**Comment by rorygraves** [comment]
Believe this is fixed by @fommil  in next release.
