### ISSUE TITLE
Override branch name with environment variable

### ISSUE THREAD

**Issue by natbusa** [scoverage/sbt-coveralls#47]
Hi,

coveralls is pushing out ids rather than branch names.
Would it be possible to have an environment variable override, eg CI_BRANCH?

Code hint:

  def currentBranch: String =
    sys.env.get("CI_BRANCH").getOrElse(repository.getBranch())

**Comment by fommil** [comment]
PR? That would suit me well too.

**Comment by ncreep** [comment]
Opened a PR for this (#101).

**Comment by gslowikowski** [comment]
Fixed by #101
