### ISSUE TITLE
Source file paths not converted properly

### ISSUE THREAD

**Issue by ensonik** [scoverage/sbt-coveralls#49]
Show stopper for me. Here is what I've figured out and the steps.

#### Run "sbt coverage test coverageReport" on project

This works fine and will generate a cobertura report as expected in ```/workspace/project/target/scala-2.10/coverage-report/cobertura.xml```

Looking at the XML found in that file, here's what I see:

    <coverage line-rate="0.90" lines-covered="900" lines-valid="806" branches-covered="68" branches-valid="49" branch-rate="0.72" complexity="0" version="1.0" timestamp="1430920680420">

    <sources> 
       <source>--source</source>
       <source>/workspace/project/src/main/scala</source> 
       <source>/workspace/project/src/main/java</source>
    </sources>

    <packages>
         <package name="com.tritondigital.counters" line-rate="0.88" branch-rate="0.71" complexity="0">
         <classes>
               <class name="package" filename="com/tritondigital/counters/package.scala" line-rate="1.00" branch-rate="1.00" complexity="0">
              </class>
         ....
    </packages>

#### Run coveralls

The coveralls does the following: 

    def sourceFilenames = {
       (elem \\ "class" \\ "@filename").map{ childProjectDir + _.toString }.toSet
    }

In my case, childProjectDir is equal to ```/workspace/project```. This means that the sourceFileNames all resolve to the wrong thing because the actual source directory is missing from the path (i.e.: We are missing the ```src/main/scala``` part in the built path). 

It results in a stack trace:

    java.io.FileNotFoundException:  /workspace/project/com/tritondigital/counters/logback/LogPublisher.scala (No such file or directory)

(_notice the missing source directory above_)

I'm uncertain if this is a coveralls problem or one with the reporting ...

**Comment by gslowikowski** [comment]
In short:
`sbt-coveralls` `1.0.0` is compatible with `sbt-scoverage` `1.0.x` (latest compatible version is `1.0.4`). `sbt-coveralls` `1.1.0` will be compatible with `sbt-scoverage` `1.1.0` (and following `1.1.x` versions).

Old `cobertura.xml` file format was not proper Cobertura file format, so was changed. Unfortunately the change is not backward incompatible.

**Comment by ensonik** [comment]
Works. 

Thanks.

**Comment by JoshRosen** [comment]
If sbt-coveralls 1.0.0 is incompatible with scoverage-1.1.0+, could you please update the example in README.md to reflect this?  Right now, it seems to be recommending a configuration that won't work:

```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.1.0")

addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.0.0")
```

Other people have run into this issue as well: https://github.com/scoverage/sbt-coveralls/commit/10609426fd626b3a404efcbbb1397e3102ace8e3#commitcomment-11139440

**Comment by gslowikowski** [comment]
Fixed
