### ISSUE TITLE
make release against sbt-scoverage 1.2.0

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-coveralls#52]
I understand that the scoverage report format changed in 1.1.x so do we need any code changes to deal with that?

**Comment by gslowikowski** [comment]
I talked about it with @rorygraves long time ago, prepared some proposed code changes and ... nothing

**Comment by rorygraves** [comment]
Sorry - I've been very rubbish - I promise to look at this properly after ScalaDays

**Comment by fommil** [comment]
bumping version

**Comment by fommil** [comment]
@sksamuel ! Ping

**Comment by sksamuel** [comment]
What do you need me to do

**Comment by fommil** [comment]
update to handle the new scoverage format (has somebody done this maybe) and then make a release

**Comment by sksamuel** [comment]
The scoverage format hasn't changed in ages? If it changed in 1.1.1 I don't remember changing it.

**Comment by fommil** [comment]
@gslowikowski @rorygraves is anything needed other than a release?

**Comment by rorygraves** [comment]
This is on my list to revisit - got rather distracted by Sublime after ScalaDays.  I can't remember if anything was outstanding - needs a retest

**Comment by rorygraves** [comment]
Will try and get to this in the next week - it would be awesome to have coverage/coveralls fully working again.

**Comment by sksamuel** [comment]
Let me know when you want a release

**Comment by Kevin-Lee** [comment]
Maybe [it's a relevant issue](/scoverage/sbt-coveralls/issues/57#issuecomment-124559188)?

**Comment by Kevin-Lee** [comment]
Any progress? As I mentioned here https://github.com/scoverage/sbt-coveralls/issues/57#issuecomment-124559188, sbt-coveralls 1.0.0 doesn't seem to work well with sbt-scoverage 1.3.0.

--------------
@rorygraves and @sksamuel, I've tested sbt-coveralls 1.0.0 with sbt-scoverage 1.3.0 stored in @sksamuel's bintray repo and it doesn't work.

I'm not sure if it's `sbt-scoverage issue`'s issue or `sbt-coveralls`'s though.

For the details, please have a look at https://semaphoreci.com/kevin-lee/skala/branches/master/builds/19

It says
```
java.io.FileNotFoundException: /home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala (No such file or directory)
```

`/home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala`? Is it ignoring the source hierarchy? Or that's supposed to be a test result?

The actually source file is in the `src/main/scala/` directory. So it's `/home/runner/skala/src/main/scala/cc/kevinlee/skala/math/CommonMath.scala`
NOT
`/home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala`.

**Comment by fommil** [comment]
I think this ticket is already out of date. Also sbt-coveralls is currently broken anyway. @Kevin-Lee best thing you could do would be to try and see how to fix this plugin against the latest scoverage :-)

**Comment by Kevin-Lee** [comment]
@fommil Alright. Let me try it. :smiley: Or... Master Yoda said, do or do not there is no try. So I guess I'll do. :smile:  Thanks.

**Comment by gvolpe** [comment]
I'm trying to use sbt-coveralls 1.0.0 with sbt-scoverage 1.1.0 and it's not working. Why is this issue closed? Any fix out there?
