### ISSUE TITLE
Git repository should be configurable

### ISSUE THREAD

**Issue by iphydf** [scoverage/sbt-coveralls#54]
https://github.com/scoverage/sbt-coveralls/blob/master/src/main/scala/org/scoverage/coveralls/CoverallsPlugin.scala#L72

In my projects, the sbt root directory is not the one that contains `.git`. If I `ln -s` the .git directory to the sbt root directory, I get [FileNotFoundException](https://travis-ci.org/iphydf/tox4j/builds/68507602#L2800)s because it's looking for the source files in the sbt root directory directly. So, my sources are in "projects/tox4j/src/main/java/.", but it looks in "projects/tox4j/.". The workaround is to `ln -s` those, as well.

**Comment by iphydf** [comment]
That second problem (which I hope is related to the first one) is actually [really annoying](https://coveralls.io/builds/2920720/source?filename=im%2Ftox%2Ftox4j%2Fimpl%2Fjni%2FToxCoreImpl.scala). I can no longer see the sources in the coveralls UI.

**Comment by kailuowang** [comment]
+1. In my project the sbt project isn't in the git root.

**Comment by davidrpugh** [comment]
+1 My project the sbt project also isn't in the git root.

**Comment by smur89** [comment]
+1 would be great to get this in

**Comment by stephen-lazaro** [comment]
I was actually just irritated by this and started to work on it. If it's not a problem, I'll open a PR in a few days with a candidate.
