### ISSUE TITLE
sbt-coveralls doesn't work when SourceForge is down.

### ISSUE THREAD

**Issue by Kevin-Lee** [scoverage/sbt-coveralls#57]
Currently, sbt-coveralls doesn't function at all because SourceForge's repository service is down.
I'm not sure if it's avoidable by sbt-coveralls though.

So what's happening is that at some point of `coveralls` task, cobertura might be used and the XML generated by it or some other library uses the DTD located at http://cobertura.sourceforge.net/xml/coverage-04.dtd

However, [SourceForge is not functioning well](https://twitter.com/sfnet_ops/status/622236074052464641).

That `coverage-04.dtd` page gives
![damn-source-forge2](https://cloud.githubusercontent.com/assets/2307335/8765465/a069fe3c-2e50-11e5-84c2-7647154a4414.png)

So when running `sbt coveralls`, I get this.

![damn-source-forge](https://cloud.githubusercontent.com/assets/2307335/8765468/b75ecdde-2e50-11e5-86fb-f7bb60391b13.png)

Is there a way to workaround? Or should it be fixed by sbt-scoverage or cobertura?

**Comment by rorygraves** [comment]
Looks like they have moved to github:


https://github.com/cobertura/cobertura

https://github.com/cobertura/cobertura/blob/master/cobertura/src/site/htdocs/xml/coverage-04.dtd

We should definately update to either point here or host the file locally.

**Comment by Kevin-Lee** [comment]
@rorygraves Yes, that would be really nice. :+1: I hope that will happen soon. :smile: Thank you.

**Comment by Kevin-Lee** [comment]
It's still down which means sbt-coveralls does not work at all (for more than three days).
http://cobertura.sourceforge.net/xml/coverage-04.dtd

Is it going to be fixed and released anytime soon?

**Comment by rorygraves** [comment]
Please see:
https://github.com/scoverage/sbt-coveralls/issues/56#issuecomment-123051088

**Comment by Kevin-Lee** [comment]
@rorygraves That's great! Thank you! :+1:

**Comment by Kevin-Lee** [comment]
Ha... that ticket was created before I reported it. How did I miss it! :disappointed_relieved: Sorry about the duplicate. :sweat_smile:

**Comment by sksamuel** [comment]
sbt-scoverage 1.3.0 is released - note some breaking changes, mostly around the name of the import for the keys. Docs updated very soon. Please test for coverals.

**Comment by Kevin-Lee** [comment]
@sksamuel Cool! Thank you. Sure, I'll test it. :+1:

**Comment by Kevin-Lee** [comment]
@sksamuel I got the following error.
```
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scoverage#sbt-scoverage;1.3.0: not found
```

**Comment by Kevin-Lee** [comment]
By the way, is sbt-coveralls 1.0.0 compatible with sbt-scoverage 1.3.0?

**Comment by sksamuel** [comment]
Yes it should be. Looks like it didn't sync onto sbt plugins repo properly because they've changed the way it works again. Why they can't be happy with one way I don't know.

**Comment by Kevin-Lee** [comment]
@sksamuel Oh...too bad. So was it not properly deployed to the sb plugin repo? Or just takes time to sync?

**Comment by sksamuel** [comment]
I don't know, someone is looking into it for me.

**Comment by Kevin-Lee** [comment]
@sksamuel OK, I'll test it when it's available. Thank you.

**Comment by Kevin-Lee** [comment]
@sksamuel I've just tested 1.3.0 stored in your bintray repo and it doesn't work.

I'm not sure if it's `sbt-scoverage issue`'s issue or `sbt-coveralls`'s though.

For the details, please have a look at https://semaphoreci.com/kevin-lee/skala/branches/master/builds/19

It says
```
java.io.FileNotFoundException: /home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala (No such file or directory)
```

`/home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala`? Is it ignoring the source hierarchy? Or that's supposed to be a test result?

The actually source file is in the `src/main/scala/` directory. So it's `/home/runner/skala/src/main/scala/cc/kevinlee/skala/math/CommonMath.scala`
NOT
`/home/runner/skala/cc/kevinlee/skala/math/CommonMath.scala`.

**Comment by aborg0** [comment]
I can [confirm](https://travis-ci.org/mind-era/zizized/builds/72664001) the problem of @Kevin-Lee in our project too. Though I had [similar problem](https://travis-ci.org/mind-era/zizized/builds/72305063) with version 1.2.0 of sbt-scoverage. (It worked before with version 1.0.4 version of sbt-scoverage, though I used jdk7 before (which I doubt it would make a difference).)
Probably sbt-scoverage output is no longer compatible with sbt-coveralls?
