### ISSUE TITLE
sources not uploaded to coveralls for multi-project builds

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-coveralls#60]
Although the latest fix now means that the final coverage number is pushed to coveralls, the files don't actually appear, e.g. https://coveralls.io/builds/3476548

**Comment by fommil** [comment]
yeah, just checked the `coveralls.json`... it's miniscule and no line info in there.

**Comment by fommil** [comment]
ok, the `coveralls.json` doesn't seem to have **any** numbers in it... so I don't know how coveralls manage to report anything :-/

**Comment by fommil** [comment]
I didn't really review the patch from @mkokho so I think it probably needs a closer look.

Basically when I mean a multi-project build I really mean that I've aggregated all the reports from all the modules in a multi-project build.

**Comment by fommil** [comment]
example of failure:

```
https://github.com/ensime/ensime-server/
cd ensime-server
# add your locally published version of sbt-coveralls to project/plugins.sbt
sbt gen-ensime
sbt coverage test it:test
sbt coverageAggregate
sbt coveralls
```

**Comment by alexflav23** [comment]
+1

**Comment by alexflav23** [comment]
@theon Any thoughts on this? I am very happy to help with the fix if you could point me in the right direction, I don't have the full bandwidth for exploratory surgery.

**Comment by alexflav23** [comment]
Hi @sksamuel @rorygraves,

 This is still broken. Check the build log [here](https://travis-ci.org/websudos/morpheus/jobs/96438932#L1064) running with the latest version of `sbt-coveralls`, namely `1.0.3`.

Anything I can do to help? This is becoming a bit of an issue inside our stack.

Regards,
Flavian

**Comment by gslowikowski** [comment]
You have to run `coverageAggregate` in separate SBT run.

**Comment by gslowikowski** [comment]
Can this issue be closed?
