### ISSUE TITLE
If you cant find an aggreated coverage on multi-project print a useful message

### ISSUE THREAD

**Issue by rorygraves** [scoverage/sbt-coveralls#70]

**Comment by gslowikowski** [comment]
Fixed in [this commit](https://github.com/scoverage/sbt-coveralls/pull/41/commits/76777787e8802c32958cc89f1ea3d166fe8b7433#diff-9593edaf542a46635e8f7d4e9b9b0708R80) (part of #41).

The message `Could not find the cobertura.xml file. Did you call coverageAggregate?` is clear.
