### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by Tooa** [scoverage/sbt-coveralls#72]
Hi,

I've tried the new `sbt-coveralls` 1.0.3 version and receive the following error: 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Repository = ./.git
[error] Could not find the cobertura.xml file. Did you call coverageAggregate?
java.io.FileNotFoundException: /home/travis/build/tudarmstadt-lt/DIVID-DJ/target/scala-2.10/coverage-report/cobertura.xml (No such file or directory)
```

This is the corresponding [travis.yaml](https://github.com/tudarmstadt-lt/DIVID-DJ/blob/master/.travis.yml) file. I had this issue before (version 1.0.0) and thought it is related to the broken multi-project support.

Any thoughts? I'm guessing that the file is not written, because the logger can't be instantiated. Maybe because I have these two dependencies on my build path?

```
val logging  = "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"  
val logback  = "ch.qos.logback" % "logback-classic" % "1.1.3"           
```

**Update**:

I stumbled upon this issue https://github.com/scoverage/sbt-coveralls/issues/49 and downgraded `sbt-scoverage` to version 1.0.4. However, I receive the same error.

**Comment by sksamuel** [comment]
The logs wouldn't have anything to do with it not finding the file. Does it
actually exist? If not then you need scoverage to generate it.

**Comment by Tooa** [comment]
When running scoverage on my local machine the file is successfully generated. So Travis should also be able to generate this file with the following configuration:

```
script:
- sbt clean coverage test && sbt coverageAggregate
- sbt scalastyle --warn
- ./scripts/travis/check_codestyle.sh
- ./scripts/travis/check_commit_msgs.sh
after_success:
- sbt coveralls
```

**Comment by rorygraves** [comment]
Is after_success run in the same context? (not a clean build area).
I believe last time we used travis we did soming like:
```
script:
- sbt clean test
- sbt scalastyle --warn
- ./scripts/travis/check_codestyle.sh
- ./scripts/travis/check_commit_msgs.sh
after_success:
- sbt clean coverage test coverageAggregate coveralls 
```

Means the coverage does not interfere with the test run (making build failures faster which was an issue for us).

I can't find enough travis documentation to confirm/deny the behaviour of after_success

**Comment by Tooa** [comment]
Good point! Solved half of the problem. After changing the `travis.yaml` file, I can see an **empty** [coverage table](https://coveralls.io/builds/4392689). The [Travis  log](https://travis-ci.org/tudarmstadt-lt/DIVID-DJ/builds/95642266) indicates the successful report upload. However, there is still the logger exception:

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation

**Comment by rorygraves** [comment]
Darn, that annoying, its not working correctly and obviously the logging would be really useful.  Will try and take a look at the weekend.

**Comment by Tooa** [comment]
Cool, thank you! Let me know, if I can help you.

**Comment by gslowikowski** [comment]
I've had similar problem with logger.
Adding:
```scala
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3"
```
to `project/plugins.sbt` file should help.

**Comment by Tooa** [comment]
Closing this issue as I have no strings attached to `sbt-coveralls` anymore.
