### ISSUE TITLE
MalformedInputException when writing HTML report

### ISSUE THREAD

**Issue by cookie223** [scoverage/sbt-coveralls#88]
When running "activator clean coverage test coverageReport" on a remote machine, I met MalformedInputException.
I believe it is related to the encoding of the HTML report but I did find where I can set it.
The project is play integrated.
The remote machine is a building tool that I have minimum knowledge of.
Please let me know if you need more information.

[0m[[0minfo[0m] [0mWritten Cobertura report [/app/workspace/SNAPSHOT_BUILD_56e399e64f262d4a46091049/target/scala-2.11/coverage-report/cobertura.xml][0m
944 [0m[[0minfo[0m] [0mWritten XML coverage report [/app/workspace/SNAPSHOT_BUILD_56e399e64f262d4a46091049/target/scala-2.11/scoverage-report/scoverage.xml][0m
945 [0m[[0minfo[0m] [0mWritten HTML coverage report [/app/workspace/SNAPSHOT_BUILD_56e399e64f262d4a46091049/target/scala-2.11/scoverage-report/index.html][0m
946 java.nio.charset.MalformedInputException: Input length = 1
947     at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
948     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
949     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
950     at java.io.InputStreamReader.read(InputStreamReader.java:184)
951     at java.io.BufferedReader.fill(BufferedReader.java:161)
952     at java.io.BufferedReader.read(BufferedReader.java:182)
953     at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
954     at scala.io.Codec.wrap(Codec.scala:68)
955     at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
956     at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
957     at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
958     at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
959     at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
960     at scala.io.Source.hasNext(Source.scala:226)
961     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
962     at scala.io.Source.foreach(Source.scala:178)
963     at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
964     at scala.io.Source.addString(Source.scala:178)
965     at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
966     at scala.io.Source.mkString(Source.scala:178)
967     at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
968     at scala.io.Source.mkString(Source.scala:178)
969     at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
970     at scala.io.Source.mkString(Source.scala:178)
971     at scoverage.report.CodeGrid.source(CodeGrid.scala:63)
972     at scoverage.report.CodeGrid.<init>(CodeGrid.scala:17)
973     at scoverage.report.ScoverageHtmlWriter.filePage(ScoverageHtmlWriter.scala:78)
974     at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writeFile(ScoverageHtmlWriter.scala:44)
975     at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:37)
976     at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:37)
977     at scala.collection.immutable.List.foreach(List.scala:318)
978     at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writePackage(ScoverageHtmlWriter.scala:37)
979     at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:27)
980     at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:27)
981     at scala.collection.immutable.List.foreach(List.scala:318)
982     at scoverage.report.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:27)
983     at scoverage.ScoverageSbtPlugin$.scoverage$ScoverageSbtPlugin$$writeReports(ScoverageSbtPlugin.scala:178)
984     at scoverage.ScoverageSbtPlugin$$anonfun$coverageReport0$1.apply(ScoverageSbtPlugin.scala:70)
985     at scoverage.ScoverageSbtPlugin$$anonfun$coverageReport0$1.apply(ScoverageSbtPlugin.scala:61)
986     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
987     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
988     at sbt.std.Transform$$anon$4.work(System.scala:63)
989     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
990     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
991     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
992     at sbt.Execute.work(Execute.scala:235)
993     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
994     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
995     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
996     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
997     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
998     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
999     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
1000    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
1001    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
1002    at java.lang.Thread.run(Thread.java:745)
1003 [0m[[31merror[0m] [0m(*:[31mcoverageReport[0m) java.nio.charset.MalformedInputException: Input length = 1[0m
1004 [0m[[31merror[0m] [0mTotal time: 4 s, completed Jul 29, 2016 6:18:07 PM[0m

**Comment by diversit** [comment]
Having exact the same problem running a stage in Jenkins 2 where the build is run using Docker.
Any progress on this issue?
Any idea how to solve this?

**Comment by gslowikowski** [comment]
Source files encoding should be **always** specified in `scalacOptions` setting, e.g. 
```scala
    scalacOptions ++= Seq("-encoding", "utf-8"),
```
Scoverage finds it there. If not specified, platform encoding is used which may be different on different machines.

Problem fixed in `sbt-scoverage` since version `1.4.0`.

Related issues:
scoverage/scalac-scoverage-plugin#134
scoverage/sbt-scoverage#155
